### ISSUE TITLE
Renderers that need "this"

### ISSUE THREAD

**Issue by robrez** [web-padawan/lit-vaadin-helpers#9]
# Background

There are some pain points we've hit a bit when renderers need "this"... the following notes are based on traditional renderer binding via property.  I see that these helpers do have lit [RenderOptions](https://lit.dev/docs/api/LitElement/#RenderOptions) but a way to provide them didn't immediately jump out at me. 

## Supporting Detail

Renderers are ideally pure, they simply accept a model and produce output based on that model

```
<grid-column .renderer="${this.something}">
```

It is common, however, for the content rendered for a cell to have a need to do things on `this`. For example, adding an event listener to an element and the event listener changes local property state (on this).  In these situations, you do need to bind the renderFn to `this`

```
<grid-column .renderer="${this.something.bind(this)">
<grid-column .renderer="${(a) => this.something(a)">
```

However, you should _not_ do that inside every render of component that contains a grid -- that component might be rendering for any number of reasons and what you're doing when you bind a new instance of a property (renderer) in every render cycle is forcing the grid to completely re-render the cells for that column (you know, because you are saying "here is a new way I wish to render these things").  The pattern we've followed when renderers need "this" is as follows:

```
private boundSomethingRenderer;

constructor() {
  this.boundSomethingRenderer = this.somethingRenderer.bind(this);
}

render() {
  return html`
    <grid-column .renderer="${this.somethingRenderer}">
  `;
}
```

## Misc

Total aside / lit-specific / not really vaadin related: Some kind of binding that handles the special case where a property is a function which auto-binds to "this" (like `@`) could help here

**Comment by web-padawan** [comment]
Hi, sorry about the delay. The renderers actually get a reference from `part.options` - here is a relevant code:

https://github.com/web-padawan/lit-vaadin-helpers/blob/fd2284b0491b55103f1cdf51e38de5632501af48/src/abstract-renderer.ts#L42

And then this `host` reference is passed to the invocation of a renderer function:

https://github.com/web-padawan/lit-vaadin-helpers/blob/fd2284b0491b55103f1cdf51e38de5632501af48/src/select-renderer.ts#L14

It has been working perfectly for my use cases. Is there anything you would like to improve?

**Comment by robrez** [comment]
Ah yes, I see now.  Thanks for the info that looks very helpful indeed!
